### ISSUE TITLE
Use Socks5

### ISSUE THREAD

**Issue by bannyhm** [wzshiming/socks5#4]
Please tell me. Can I use your Socks5 solution to replace the default Socks5 FRP plugin or Socks5.apk (which I currently use) on the tunnel client side to provide UDP support in my connection scheme? And can you help me organize my wiring diagram with your tools?

![Sheme01](https://github.com/wzshiming/socks5/assets/72357001/de0da745-cff5-4b3d-abf8-90938a68fa7d)

**Comment by wzshiming** [comment]
Yes, you can use this instead of the other stuff, they're both socks5 protocols and should be seamlessly replaceable.

> And can you help me organize my wiring diagram with your tools?

What do you want?

**Comment by bannyhm** [comment]
> Yes, you can use this instead of the other stuff, they're both socks5 protocols and should be seamlessly replaceable.
> 
> > And can you help me organize my wiring diagram with your tools?
> 
> What do you want?

I need my program running on a remote Windows PC through a proxy of the socks5://<ip_server>:<port>:user:passwodr format to be able to access the Internet with the ip address of the mobile phone and UDP support.
The problem is that the phone has a dynamic ip address and it changes every 10 minutes. So I'm using a tunnel to connect to the phone via the server's public ip.

**Comment by wzshiming** [comment]
What you are saying is that for a Windows PC, through the tunnel (Linux -> phone) to access the Internet is?

As I understand it you want a Windows PC to access the private network where the Phone is located, relayed through a Linux server with a network IP.

For TCP I have an existing solution for you, for UDP since I don't have a scenario, you may have a little development work ahead of you.

**Comment by bannyhm** [comment]
I found 2 working options with TCP on the client side:
1. I am using the built-in socks5 plugin in FRP.
2. I am using the app apk "Socks Server Ultimate".

I thought that if I use your socks5 solution on the client side, then I will have udp traffic. I am very weak in development, and I thought that you have many solutions, and you are already familiar with this.

Just in case, I will send the FRP configuration, suddenly you can figure it out.

Server frps:

[common]
bind_addr = 0.0.0.0
bind_port = 9800
kcp_bind_port = 9800
dashboard_addr = 0.0.0.0
dashboard_port = 9500
dashboard_user = user
dashboard_pwd = user
enable_prometheus = true
detailed_errors_to_client = true
authentication_method = token
authenticate_heartbeats = false
authenticate_new_work_conns = false
token = 12345678
oidc_issuer =
oidc_audience =
oidc_skip_expiry_check = false
oidc_skip_issuer_check = false
allow_ports = 2000-7000,7001,7003,8000-60000
max_pool_count = 0
max_ports_per_client = 0
tls_only = false
subdomain_host = frps.com
tcp_mux = true
udp_packet_size = 1500
dns_server = 0.0.0.0


Client frpc:

[common]
forward_all = tcp+udp
all_use_encryption = false
all_use_compression = false
server_addr = 188.xxx.xxx.xxx
server_port = 9800
plugin_user = user
plugin_passwd = user
authentication_method = token
token = 12345678
dns_server = 10.205.171.77

udp_forward = true

[web_tcp6395]
type = tcp
local_ip = 127.0.0.1
local_port = 6396
remote_port = 6396
use_encryption = false
use_compression = false
protocol = tcp

[web_udp6395]
type = udp
local_ip = 127.0.0.1
local_port = 6395
remote_port = 6395
use_encryption = false
use_compression = false
protocol = udp

[plugin_socks5_6395]
type = tcp
remote_port = 6395
plugin = socks5
plugin_user = user
plugin_passwd = user

**Comment by wzshiming** [comment]
On the client side, using [bridge] for TCP will work, this socks5 implements UDP, but I didn't integrate it into [bridge], I was only thinking of proxying TCP.

``` bash
bridge -b 'socks5//user:pwd@0.0.0.0:6395' -b 'ssh://user:pwd@your_server:22' -p -
```

[bridge]: https://github.com/wzshiming/bridge

**Comment by bannyhm** [comment]
Thank you very much for answering me
