### ISSUE TITLE
尝试通过 Socks5 代理建立双向 QUIC 连接失败

### ISSUE THREAD

**Issue by WankkoRee** [wzshiming/socks5#7]
demo仓库：https://github.com/WankkoRee/go-http3-proxy

----

我希望通过 QUIC 的双向连接特性来实现端口穿透，即：客户端在主动访问服务端后，服务端通过已经建立起的 QUIC 连接，可以访问客户端上的服务。

未使用代理，本机直连，测试情况符合预期：

![image](https://github.com/wzshiming/socks5/assets/21287731/2ebb4c60-1c34-446b-8103-4c13a3609df8)

未使用代理，客户端位于容器内（模拟NAT网络环境），测试情况符合预期：

![image](https://github.com/wzshiming/socks5/assets/21287731/15d0ce80-a4e0-4cd7-856c-089962492e0e)

使用代理，本机直连，测试发现会变成单向连接：

![image](https://github.com/wzshiming/socks5/assets/21287731/28f91e92-e9bf-4123-8cc7-c46e09f1efa6)

我现在的需求是使用 Socks5 代理完成双向 QUIC 连接，我应该怎么改动我的代码？

----

我尝试过复写`Dialer.ProxyPacketDial`直接返回客户端服务的`PacketConn`，但是发现会报错连接已存在。

**Comment by wzshiming** [comment]
> 双向连接

你具体是只啥? 按照上下文和代码的改动, 感觉你是想做通过一次 quic+socks5 代理, 双向都能发起 http request 吧?

如果我理解的没错的话, 在标准的 socks5 定义中是没办法做到的, 你需要建立两次通过代理的 quic 通道, 一个连接按照你 fork 的项目一样使用, 另一个连接交换 client 和 server

**Comment by WankkoRee** [comment]
> 你具体是只啥? 按照上下文和代码的改动, 感觉你是想做通过一次 quic+socks5 代理, 双向都能发起 http request 吧?

是的，具体场景是：

客户端有一个监听 8081 端口的服务，服务端有一个监听 8080 端口的服务，但是客户端位于 NAT 网络中，其端口并没有对外开放，所以无法由服务端主动发起到客户端的连接。

而 QUIC 的连接具有双向性，在服务端接收到来着客户端 8081 端口的连接后，可以在已有连接上向客户端的服务发起请求（即使 IP 和端口已经因为 NAT 等原因发生改变）。

我希望由连接受限的客户端发起 QUIC 连接，服务端接收到连接后通过已有的 QUIC 连接连回客户端，这一点我已经在代码中验证可行。

但是另一方面我还需要让客户端通过代理连接到服务端，现在我卡在这一块不知道怎么解决。

----

> 如果我理解的没错的话, 在标准的 socks5 定义中是没办法做到的

那有其他代理协议可以满足这个需求吗？

----

> 你需要建立两次通过代理的 quic 通道, 一个连接按照你 fork 的项目一样使用, 另一个连接交换 client 和 server

两个连接是分别由客户端和服务端发起吗？还是都由客户端发起？如果是前者的话，没法满足我端口穿透的需求；如果是后者的话，希望能详细说明，感谢。

**Comment by wzshiming** [comment]
由客户端发起的, 但是由客户端作为服务器, 只需要把 net.Conn 包装一下, 把 net.Dial 包装成 net.Listen , net.Listen 包装成 net.Dial

**Comment by WankkoRee** [comment]
您能否抽空按照您说的方案对我的代码进行改动？已向您进行赞助。

**Comment by wzshiming** [comment]
你要做的这个, 其实我以前有计划要在 [wzshiming/bridge](https://github.com/wzshiming/bridge) 支持的, 为此我还专门[搞了个项目处理多种协议复合的情况](https://github.com/wzshiming/permuteproxy/blob/0b9f97a43266f3e52f518f9ebd297470c4e322d7/all_test.go#L101).

当时感觉这个需求比较少, 而且现有功能基本上啥功能都满足了, 后续事多了就完了这茬了...

等我有空的时候在看看.

我不太确定你的具体需求, 如果只是内网穿透, 没有必须要上 quic 的需求, 你可以研究一下 [wzshiming/bridge](https://github.com/wzshiming/bridge) 里的 ssh 协议

**Comment by wzshiming** [comment]
当然这一切都是建立在 走标准通用协议的 情况上, 如果进行魔改的话我想 `ssh+quic://` 作为一个基础, 应该可以满足所有这方面的需求

**Comment by wzshiming** [comment]
但是看起来魔改的 `quic+socks5://` 就能满足你的需求, 我不确定你是否清楚, 由于 socks5 的一些特性会导致 quic 的能力丢失(client IP 可以随便变, 弱网, 避免监测)

**Comment by WankkoRee** [comment]
可能我对需求的表述有点偏差，使用 QUIC 对我来说是必要条件，因为我这边客户端和服务端上的 QUIC 都是有实际接口存在的。

所以我希望有代理能够满足双向 QUIC 的负载，而不是通过魔改协议实现代理打洞。

**Comment by wzshiming** [comment]
简单封装了一下, 应该满足你的需求 https://github.com/wzshiming/quic-over-proxy

**Comment by WankkoRee** [comment]
感谢！我去测试。

**Comment by WankkoRee** [comment]
看了下，惊为天人，核心代码应该是这个？

https://github.com/wzshiming/quic-over-proxy/blob/c5b9551e64098ebf86e5065cd219a2ec2a5056d4/dialer.go#L54-L58

不过十分不好意思，我现在才明白过来您说的两个连接的方案是这样子。
这样的话和我实际需求不太一样，我这边是必须复用同一个连接而且不允许改动服务端。
（其实复用同一个连接的需求也是服务端那边的，服务端的逻辑是收到来自客户端的连接后直接通过已有连接连上RemoteAddr）
所以非常抱歉您的代码没法满足我的需求。不过还是万分感谢，您的代码在其他情况下很有价值。

----

另外，这是否就是您说的“在标准的 socks5 定义中是没办法做到的”，那是否有其他代理可以实现呢？

**Comment by wzshiming** [comment]
其实可以复用一个链接 你把dial 和listen合并一起就能复用了 但是这已经算是 有点魔改了

**Comment by wzshiming** [comment]
服务端不改咋加支持

**Comment by WankkoRee** [comment]
> 服务端不改咋加支持

因为我最开始尝试的时候，发现软路由上的 VMess 透明代理能非侵入地完成我的需求，所以我才确信只改动客户端的情况下也能实现我的需求。

**Comment by WankkoRee** [comment]
当时测试的时候，就是在我仓库代码不走代码层面的代理的情况下，客户端发起的连接直接经过软路由的代理到了服务端，服务端那边的RemoteAddr也是软路由的代理IP，而且双向数据流是正常的。

**Comment by wzshiming** [comment]
哦, 那其实就是 VPN 了嘛, 这已经不算是应用层的协议了, 你需要看 L3/L4 方向了

**Comment by WankkoRee** [comment]
好的，再次感谢您的帮助。
